// Generated by scripts/bundle-stats.mjs — do not edit by hand.
export const bundleStats = {
  "generatedAt": "2026-09-30",
  "packages": [
    {
      "id": "@atolljs/core",
      "label": "core",
      "main": {
        "min": 31144,
        "gzip": 10432
      },
      "worker": {
        "min": 24521,
        "gzip": 8466
      }
    },
    {
      "id": "@atolljs/react",
      "label": "react",
      "main": {
        "min": 352,
        "gzip": 239
      }
    },
    {
      "id": "@atolljs/vue",
      "label": "vue",
      "main": {
        "min": 346,
        "gzip": 236
      }
    },
    {
      "id": "@atolljs/solidjs",
      "label": "solidjs",
      "main": {
        "min": 372,
        "gzip": 254
      }
    },
    {
      "id": "@atolljs/svelte",
      "label": "svelte",
      "main": {
        "min": 533,
        "gzip": 283
      }
    },
    {
      "id": "@atolljs/angular",
      "label": "angular",
      "main": {
        "min": 2387,
        "gzip": 1152
      }
    },
    {
      "id": "@atolljs/nextjs",
      "label": "nextjs",
      "main": {
        "min": 140,
        "gzip": 115
      }
    },
    {
      "id": "@atolljs/node",
      "label": "node",
      "main": {
        "min": 2169,
        "gzip": 952
      },
      "worker": {
        "min": 94,
        "gzip": 108
      }
    },
    {
      "id": "@atolljs/nestjs",
      "label": "nestjs",
      "main": {
        "min": 5101,
        "gzip": 2004
      },
      "worker": {
        "min": 1178,
        "gzip": 641
      }
    },
    {
      "id": "@atolljs/islands",
      "label": "islands",
      "main": {
        "min": 9744,
        "gzip": 3916
      },
      "worker": {
        "min": 33832,
        "gzip": 10518
      }
    },
    {
      "id": "@atolljs/react-island",
      "label": "react-island",
      "main": {
        "min": 3220,
        "gzip": 1499
      },
      "worker": {
        "min": 7626,
        "gzip": 2758
      }
    },
    {
      "id": "@atolljs/vue-island",
      "label": "vue-island",
      "main": {
        "min": 3815,
        "gzip": 1539
      },
      "worker": {
        "min": 3539,
        "gzip": 1660
      }
    },
    {
      "id": "@atolljs/svelte-island",
      "label": "svelte-island",
      "main": {
        "min": 1586,
        "gzip": 814
      },
      "worker": {
        "min": 2233,
        "gzip": 973
      }
    },
    {
      "id": "@atolljs/solid-island",
      "label": "solid-island",
      "main": {
        "min": 3241,
        "gzip": 1514
      },
      "worker": {
        "min": 4782,
        "gzip": 2045
      }
    },
    {
      "id": "@atolljs/angular-island",
      "label": "angular-island",
      "main": {
        "min": 2210,
        "gzip": 938
      },
      "worker": {
        "min": 6424,
        "gzip": 2794
      }
    }
  ],
  "dependencies": [
    {
      "id": "zod",
      "note": "mz() / listSchema() — atoll pulls a narrowed surface",
      "min": 92598,
      "gzip": 24605
    },
    {
      "id": "msgpackr",
      "note": "msgpackrCodec",
      "min": 29699,
      "gzip": 10852
    },
    {
      "id": "@msgpack/msgpack",
      "note": "msgpackCodec",
      "min": 21923,
      "gzip": 6097
    },
    {
      "id": "solid-js",
      "note": "core deps; solidjs/solid-island peers",
      "min": 22349,
      "gzip": 8370
    },
    {
      "id": "htmlparser2",
      "note": "islands worker",
      "min": 26965,
      "gzip": 6508
    },
    {
      "id": "react-reconciler",
      "note": "react-island worker (React apps)",
      "min": 129086,
      "gzip": 39326
    }
  ]
} as const;
