// Generated by scripts/island-perf.mjs — do not edit by hand.
export const islandPerfStats = {
  "generatedAt": "2026-09-29",
  "rows": 200,
  "results": [
    {
      "id": "imp",
      "label": "Imperative (no framework)",
      "scenarios": {
        "mount": {
          "workerMs": 1.6,
          "mainMs": 5.9,
          "ops": 2608
        },
        "update": {
          "workerMs": 7.8,
          "mainMs": 8.6,
          "ops": 2609
        },
        "click": {
          "workerMs": 1.1,
          "mainMs": 0.1,
          "ops": 1
        }
      }
    },
    {
      "id": "react",
      "label": "React",
      "scenarios": {
        "mount": {
          "workerMs": 6.5,
          "mainMs": 4,
          "ops": 2007
        },
        "update": {
          "workerMs": 8.5,
          "mainMs": 0.7,
          "ops": 802
        },
        "click": {
          "workerMs": 6.5,
          "mainMs": 0.1,
          "ops": 603
        }
      }
    },
    {
      "id": "vue",
      "label": "Vue",
      "scenarios": {
        "mount": {
          "workerMs": 2.2,
          "mainMs": 3.4,
          "ops": 2408
        },
        "update": {
          "workerMs": 3.6,
          "mainMs": 0.6,
          "ops": 200
        },
        "click": {
          "workerMs": 0.8,
          "mainMs": 0,
          "ops": 1
        }
      }
    },
    {
      "id": "svelte",
      "label": "Svelte",
      "scenarios": {
        "mount": {
          "workerMs": 9.2,
          "mainMs": 7.2,
          "ops": 3445
        },
        "update": {
          "workerMs": 4.7,
          "mainMs": 0.1,
          "ops": 200
        },
        "click": {
          "workerMs": 0.4,
          "mainMs": 0,
          "ops": 1
        }
      }
    },
    {
      "id": "solid",
      "label": "SolidJS",
      "scenarios": {
        "mount": {
          "workerMs": 2,
          "mainMs": 5.5,
          "ops": 2809
        },
        "update": {
          "workerMs": 3.7,
          "mainMs": 0.1,
          "ops": 200
        },
        "click": {
          "workerMs": 0.3,
          "mainMs": 0,
          "ops": 1
        }
      }
    },
    {
      "id": "ng",
      "label": "Angular",
      "scenarios": {
        "mount": {
          "workerMs": 4.2,
          "mainMs": 6.1,
          "ops": 3015
        },
        "update": {
          "workerMs": 4.3,
          "mainMs": 0.1,
          "ops": 200
        },
        "click": {
          "workerMs": 0.7,
          "mainMs": 0,
          "ops": 1
        }
      }
    }
  ]
} as const;
