#!/usr/bin/env node
// Assemble the unpacked Chrome extension in dist/ (chrome://extensions →
// "Load unpacked"). No bundler: the dashboard app is copied verbatim from
// packages/devtools/app, and app/panel.html is index.html plus the
// extension bootstrap (ext/bridge.js) and stylesheet (ext/ext.css). The
// one generated script is content.js (manifest content scripts can't be
// modules): src/frames.js + src/content.js with import/export stripped.
//
//   node packages/devtools-extension/scripts/build.mjs [outDir]
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { markPng } from './icons.mjs';

const pkgDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repo = resolve(pkgDir, '../..');

export const ICON_SIZES = [16, 32, 48, 128];
const MAIN_SCRIPT = '<script type="module" src="./main.js"></script>';

/** Chrome `version` is 1-4 dot-separated integers; a semver prerelease moves to `version_name`. */
export function chromeVersion(semver) {
  const core = /^(\d+)\.(\d+)\.(\d+)/.exec(semver);
  if (!core) throw new Error(`unsupported version ${semver}`);
  const version = core.slice(1).map(Number).join('.');
  return version === semver ? { version } : { version, version_name: semver };
}

/** index.html → panel.html: the extension stylesheet + bridge go in, nothing else changes. */
export function panelHtml(indexHtml) {
  // Extension pages run under script-src 'self': an inline script would be
  // blocked, so fail the build instead of shipping a dead panel.
  if (/<script\b(?![^>]*\bsrc=)[^>]*>/i.test(indexHtml)) {
    throw new Error('app/index.html has an inline <script>; extension pages only allow external scripts');
  }
  if (!indexHtml.includes(MAIN_SCRIPT)) throw new Error(`app/index.html: ${MAIN_SCRIPT} not found`);
  if (!indexHtml.includes('</head>')) throw new Error('app/index.html: </head> not found');
  return indexHtml
    .replace('</head>', '  <link rel="stylesheet" href="../ext/ext.css" />\n</head>')
    .replace(MAIN_SCRIPT, `<script type="module" src="../ext/bridge.js"></script>\n  ${MAIN_SCRIPT}`);
}

/**
 * ES module sources → one classic script. Only the forms these files use
 * are handled (single-line `import { … } from './x.js';`, `export` before a
 * declaration); anything else fails the build rather than shipping a
 * script Chrome would reject.
 */
export function classicScript(sources, footer) {
  const body = sources.map(({ name, code }) => {
    const out = code
      .replace(/^import\s*\{[^}]*\}\s*from\s*'\.\/[\w-]+\.js';\r?\n/gm, '')
      .replace(/^export\s+(?=(?:async\s+)?function\b|const\b|let\b|class\b)/gm, '');
    if (/^\s*(?:import|export)\b/m.test(out)) throw new Error(`${name}: unsupported import/export form for the classic content script`);
    return `// ${name}\n${out.trim()}\n`;
  });
  return `// Generated by scripts/build.mjs, do not edit.\n${body.join('\n')}\n${footer}\n`;
}

export function build({
  outDir = join(pkgDir, 'dist'),
  appDir = join(repo, 'packages/devtools/app'),
  iconSvg = join(repo, 'docs-consumer/public/atoll-icon-dark.svg'),
} = {}) {
  const src = join(pkgDir, 'src');
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(join(outDir, 'ext'), { recursive: true });
  mkdirSync(join(outDir, 'icons'), { recursive: true });

  cpSync(appDir, join(outDir, 'app'), {
    recursive: true,
    filter: (p) => !p.endsWith('.d.ts'),
  });
  writeFileSync(join(outDir, 'app/panel.html'), panelHtml(readFileSync(join(appDir, 'index.html'), 'utf8')));

  for (const f of ['devtools.html', 'devtools.js', 'background.js']) cpSync(join(src, f), join(outDir, f));
  for (const f of ['bridge.js', 'push-bridge.js', 'hub.js', 'frames.js', 'ext.css']) cpSync(join(src, f), join(outDir, 'ext', f));
  // Top-level `const` stays in the content script's isolated world (the page can't see it);
  // it lets a browser test read the relay state through that world's execution context.
  writeFileSync(join(outDir, 'content.js'), classicScript(
    ['frames.js', 'content.js'].map((name) => ({ name, code: readFileSync(join(src, name), 'utf8') })),
    'const atollContentRelay = installContentRelay({ runtime: chrome.runtime });',
  ));

  const svg = readFileSync(iconSvg, 'utf8');
  for (const s of ICON_SIZES) writeFileSync(join(outDir, `icons/icon-${s}.png`), markPng(svg, s));

  // The extension ships the dashboard app, so it carries @atolljs/devtools' version.
  const { version } = JSON.parse(readFileSync(join(repo, 'packages/devtools/package.json'), 'utf8'));
  const manifest = { ...JSON.parse(readFileSync(join(src, 'manifest.json'), 'utf8')), ...chromeVersion(version) };
  writeFileSync(join(outDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);

  const referenced = [
    manifest.devtools_page, manifest.background.service_worker, ...manifest.content_scripts.flatMap((c) => c.js),
    ...Object.values(manifest.icons), 'app/panel.html', 'app/main.js', 'ext/hub.js', 'ext/push-bridge.js', 'ext/frames.js',
  ];
  const missing = referenced.filter((f) => !existsSync(join(outDir, f)));
  if (missing.length) throw new Error(`extension build is missing: ${missing.join(', ')}`);
  return { outDir, manifest };
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const { outDir, manifest } = build(process.argv[2] ? { outDir: resolve(process.argv[2]) } : {});
  console.log(`atoll devtools extension ${manifest.version} → ${outDir}`);
  console.log('load it: chrome://extensions → Developer mode → Load unpacked → that folder');
}
