/**
 * Regenerates docs-consumer/src/islandPerfStats.ts — the measured
 * worker-vs-main processing split per island framework, shown by the
 * "Processing load" section of the Bundle size docs page.
 *
 * Runs packages/islands/test/islandBench.test.ts (which mounts the same
 * 200-row tree through every island adapter and times each side), scrapes
 * the `[bench-stats] {json}` line from vitest's stdout, and writes it out
 * as a typed const. Rounding to 1 decimal keeps the generated file stable
 * across runs on the same machine.
 *
 * Run: node scripts/island-perf.mjs   (npm run stats:islands)
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(new URL('.', import.meta.url)));
const OUT = path.join(ROOT, 'docs-consumer/src/islandPerfStats.ts');

let stdout;
try {
  stdout = execFileSync(
    process.execPath,
    ['node_modules/vitest/vitest.mjs', 'run', 'packages/islands/test/islandBench.test.ts'],
    { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'] },
  );
} catch (e) {
  stdout = e.stdout ?? '';
  console.error('bench spec failed — see output above');
  process.exit(1);
}

const line = stdout.split('\n').find((l) => l.includes('[bench-stats]'));
if (!line) {
  console.error('no [bench-stats] line in vitest output');
  process.exit(1);
}
const raw = JSON.parse(line.slice(line.indexOf('[bench-stats]') + '[bench-stats]'.length));

const round = (o) =>
  Array.isArray(o)
    ? o.map(round)
    : o && typeof o === 'object'
      ? Object.fromEntries(
          Object.entries(o).map(([k, v]) => [
            k,
            typeof v === 'number' ? Math.round(v * 10) / 10 : round(v),
          ]),
        )
      : o;

const stats = round(raw);

fs.writeFileSync(
  OUT,
  '// Generated by scripts/island-perf.mjs — do not edit by hand.\n' +
    `export const islandPerfStats = ${JSON.stringify(stats, null, 2)} as const;\n`,
);
console.log(`wrote ${path.relative(ROOT, OUT)}`);
for (const r of stats.results) {
  const s = r.scenarios;
  const w = s.mount.workerMs + s.update.workerMs + s.click.workerMs;
  const m = s.mount.mainMs + s.update.mainMs + s.click.mainMs;
  console.log(
    `${r.label.padEnd(28)} worker ${w.toFixed(1)}ms  main ${m.toFixed(1)}ms  → worker ${Math.round((100 * w) / (w + m))}%`,
  );
}
